name:                todo
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/todo#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2022 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  todo:
    source-dirs:      src
    main:             Main.hs
